 This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    For more information visit http://rptl.io/venv

Traceback (most recent call last):
  File "/home/pi/myenv/lib/python3.11/site-packages/mysql/connector/connection_cext.py", line 755, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Incorrect double value: '' for column `data`.`SensorData`.`humidity` at row 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/dhtdb.py", line 65, in <module>
    main()
  File "/home/pi/dhtdb.py", line 59, in main
    save_to_db(timestamp, humidity, temperature)
  File "/home/pi/dhtdb.py", line 27, in save_to_db
    cursor.execute(query, values)
  File "/home/pi/myenv/lib/python3.11/site-packages/mysql/connector/cursor_cext.py", line 351, in execute
    self._connection.cmd_query(
  File "/home/pi/myenv/lib/python3.11/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/myenv/lib/python3.11/site-packages/mysql/connector/connection_cext.py", line 763, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.DataError: 1366 (22007): Incorrect double value: '' for column `data`.`SensorData`.`humidity` at row 1
